name: Node.js CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
        node-version:
          - 12.x
          - 14.x
          - 16.x

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run types:check
      - run: npm run format:check
      - run: npm run lint
      - run: npm run test:ci
      - run: npm run compile
        env:
          CI: true
